spring:
  application:
    name: RedisStudy
  datasource:
    driver-class-name: org.postgresql.Driver

  # session 설정(redis)
  session:
    store-type: redis
    redis:
      namespace: "spring:session"
  data:
    redis:
      cluster:
        nodes:
          - localhost:7001
          - localhost:7002
          - localhost:7003

  # 캐시 사용
  cache:
    type: redis

# session 설정
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID # session 이름 설정
      timeout: 60m       # session 만료시간 설정

--- #dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/redis
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true        #SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  #SQL 쿼리를 가독성 좋게 줄바꿈 및 들여쓰기해서 포맷팅
    open-in-view: false