spring:
  application:
    name: RedisStudy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  session:
    store-type: redis
    redis:
      namespace: "spring:session:myapp"
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 1 #세션 전용 DB

  cache: #캐시 사용
    type: redis
